# set offset of drones
# T letter
size: 6

mavros0:
  x: 0.0
  y: -3.0
  z: 11.0

mavros1:
  x: 0.0
  y: -1.0
  z: 11.0
  
mavros2:
  x: 0.0
  y: 1.0
  z: 11.0

mavros3:
  x: 0.0
  y: 3.0
  z: 11.0
  
mavros4:
  x: 0.0
  y: 0.0
  z: 8.0
  
mavros5:
  x: 0.0
  y: 0.0
  z: 5.0
  
